### ISSUE TITLE
context in action functions

### ISSUE THREAD

**Issue by rns** [rns/kollos-luif-doc#11]
`action` adverb for LUIF structural rules value of `function(...) block end` -- it will need context info. Will it be provided via accessors in a separate namespace (like `Marpa::R2::Context`) or actions will be treated as methods of some inheritable LUIF object?

**Comment by jeffreykegler** [comment]
There's lots of stuff I left unspecified about the actions -- for example, the LUIF should treat RHS symbols which occur inside it as values and substitute references to the appropriate child value.  And there should be a way of dealing with a RHS like

```
    X ::= A J A K L A
```

so that you can refer to the 2nd of the 3 `A`'s.  (`A:2` is my idea.).  Also, I think we should allow the angle bracketed form: `<J>` and `<A:2>`.  There should be a "raw Lua" way to refer to the RHS values.

And, yes, there should be context accessors of some form.  If you want to work this out, feel free to include your own ideas.

**Comment by rns** [comment]
I've put my ideas in [this manual.md section](https://github.com/rns/kollos-luif-doc/blob/master/manual.md#context-accessors-) for your review.

**Comment by jeffreykegler** [comment]
I commented in #26.  Probably should have done so in this issue, but too
much to remember. :-)

**Comment by rns** [comment]
Great, this one a candidate for closing. :)

**Comment by jeffreykegler** [comment]
I agree, but do not have permission to close issues in this repo.

**Comment by rns** [comment]
Ah, yes. [Now you have](https://github.com/rns/kollos-luif-doc/settings/collaboration).
